---
title: "graphs_per_year"
author: "Jaime Jacob"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Upload CSV

```{r}
dev.off()
stocking <- read.csv("/Users/jaimejacob/Documents/urop/condense_lines_proj/find_keywords2/formatted_years/formatted_years_stocking.csv")
eradication <- read.csv("/Users/jaimejacob/Documents/urop/condense_lines_proj/find_keywords2/formatted_years/formatted_years_eradication.csv")
regulation <- read.csv("/Users/jaimejacob/Documents/urop/condense_lines_proj/find_keywords2/formatted_years/formatted_years_regulation.csv")
habitat_management <- read.csv("/Users/jaimejacob/Documents/urop/condense_lines_proj/find_keywords2/formatted_years/formatted_years_habitat.csv")

plot.matrix <- matrix(c(1, 3, 5, 7, 
                        2, 4, 6, 8), 
                        nrow = 4, ncol = 2)
plot.matrix
cex.axis   <- 1.2
col.bords  <- "gray60"
layout(mat = plot.matrix, widths = c(1,3))
size.point <- 1.2
cols_mat <- c("lightblue", "lightpink", "lightgreen", "lightyellow")
#par(oma = c(6, 4, 0, 2))
#mar.left   <-  c(0, 2, 1.5, 2)
#mar.right  <-  c(0, 2, 1.5, 4)
par(mar=c(1,0,2,2), family = "Optima", oma = c(4,5,4,4))
axis.cols  <- c("white", "white", "white", "white", "black", "white", "white" ) # show on bottom row
cex.labs <- 1.2
main_labels = c("Stocking", "Eradication", "Regulation", "Habitat Management")
file_paths = c(stocking, eradication, regulation, habitat_management)



plot_box <- function(file_path, name, color, xaxis.col, xaxis.label, yaxis.col, yaxis.label){
  years <- file_path$DATE
  contains_years <- grepl("[^0-9]", years)
  non_numeric_indices <- !grepl("^[0-9]+$", years)
  years[!grepl("[^0-9]", years)]
  years[non_numeric_indices] <- NA
  years <- na.omit(years)
  years <- as.integer(years)
  years <- years[(years < 2000) & (years > 1900)]
  max(years)
  head(years)
  head(contains_years)
  # title <- name + ' Years'
  boxplot(years,
          main = "", 
          xlab = "",         
          ylab = name,         
          col = color,
          ylim=c(1900,2000),
          family = "Optima",
          horizontal=TRUE,
          axes=FALSE)
  
   axis (side = 1,                        
      at = c(1900, 1925, 1950, 1975, 2000),
      labels = c("1900", "1925", "1950", "1975", "2000"), 
      cex.axis = 1.2,
      las = 1,
      col = xaxis.col,
      col.axis = xaxis.label,
      family = "Optima")
   
         mtext (side = 3, text = name,
       outer = FALSE, cex = 0.8, col = "black", adj = 0, line = -0.55,family = "Optima")
   
  hist(years,
     main = "",  
     xlab = "",                   
     ylab = "",              
     col = color,                 
     border = "black",
    breaks = seq(1900, 2000, by = 5), 
    family = "Optima",
    axes = FALSE
    )
  
     axis (side = 1,                        
      at = c(1900, 1925, 1950, 1975, 2000),
      labels = c("1900", "1925", "1950", "1975", "2000"), 
      cex.axis = 1.2,
      las = 1,
      col = xaxis.col,
      col.axis = xaxis.label,
      family = "Optima")
     
      axis (side = 4,                        
      at = c(0, 50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600),
      labels = c("0", "50", "100", "150", "200", "250", "300", "350", "400", "450", "500", "550", "600"), 
      cex.axis = 1.2,
      las = 1,
      col = "black",
      col.axis = "black",
      family = "Optima")
      



  
}


```

```{r}

col.axes  <- c("gray60", "white", "black") 


plot_box(stocking, 'Stocking', "lightblue", col.axes[1], col.axes[2])

plot_box(eradication, 'Eradication', "lightpink", col.axes[1], col.axes[2])

plot_box(regulation, 'Regulation', "lightgreen", col.axes[1], col.axes[2])

plot_box(habitat_management, 'Habitat Management', "lightyellow", col.axes[3], col.axes[3])

mtext (side = 4, text = "Frequency",
       outer = TRUE, cex = 1, line = 2, col = "black", family = "Optima")
mtext (side = 1, text = "Year",
       outer = TRUE, cex = 1, line = 2, col = "black", family = "Optima")
mtext (side = 3, text = "Distibution over Time of Management Strategies",
       outer = TRUE, cex = 1, line = 2, col = "black", family = "Optima")


```

